version: "3"
services:
  opentelemetry-collector-contrib:
    image: otelcontribcol
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
    - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    - ./varlogspods:/var/log/pods